# pyproject.toml
[project]
name = "fastapi-backend"
version = "0.1.0"
description = "FastAPI backend"
requires-python = ">=3.8"

dependencies = [
    "fastapi[all]",
    "uvicorn",
    "pydantic",
    "sqlalchemy",
    "alembic",
    "psycopg2-binary",
    "python-dotenv"
]


